# Generated by Django 3.2.13 on 2022-06-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_producto_imagen_producto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='id Cliente')),
                ('rut_cli', models.CharField(max_length=11, verbose_name='Rut Clienet')),
                ('nombre_cli', models.CharField(max_length=40, verbose_name='Nombre_prod')),
                ('email', models.CharField(max_length=40, verbose_name='Email')),
                ('direccion', models.CharField(max_length=40, verbose_name='Direccion Cli')),
                ('suscripcion', models.BooleanField(verbose_name='Suscripcion Cli')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('idDetVenta', models.IntegerField(primary_key=True, serialize=False, verbose_name='id Detalle Venta')),
                ('cantidad_prod_venta', models.IntegerField(verbose_name='Cantidad de productos')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.IntegerField(primary_key=True, serialize=False, verbose_name='id Venta')),
                ('fech_venta', models.DateField(verbose_name='FechaVenta')),
                ('descuento', models.IntegerField(verbose_name='Descuento Venta')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal')),
                ('iva', models.IntegerField(verbose_name='Iva')),
                ('total', models.IntegerField(verbose_name='Total')),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='descripcion_prod',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_prod',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_prod',
            field=models.ImageField(null=True, upload_to='Productos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_prod',
            field=models.CharField(max_length=40, null=True, verbose_name='Nombre_prod'),
        ),
    ]
