# Generated by Django 4.0.4 on 2022-06-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_descripcion_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_prod',
            field=models.ImageField(blank=True, null=True, upload_to='Productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_prod',
            field=models.CharField(default=12432, max_length=40, verbose_name='Nombre_prod'),
            preserve_default=False,
        ),
    ]
