# Generated by Django 3.2.13 on 2022-07-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_producto_imagen_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password_cli',
            field=models.CharField(default='0', max_length=40, null=True, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id de Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_prod',
            field=models.ImageField(blank=True, null=True, upload_to='Productos'),
        ),
    ]
