# Generated by Django 3.2.13 on 2022-07-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220707_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='suscripcion',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password_cli',
            field=models.CharField(default='12345', max_length=40, null=True, verbose_name='Contraseña'),
        ),
    ]
