# Generated by Django 3.2.13 on 2022-07-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220707_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Cliente',
        ),
    ]
